### PR TITLE
 Move Block5 MaxPooling2D  - 4th  attempt.

### PR DESCRIPTION
**Pull request by whatdhack**
The maxPooling2D does not appear to be in the right place.
    
    Added a new pooling option 'no', to make code backward compatible.

### CODE REVIEW

**Comment by taehoonlee** [comment]
Thank you for the PR, @whatdhack. What is the "right" place?

**Comment by ahundt** [comment]
I agree that there should be a way to disable the final pooling.

@whatdhack you can work around this without changing the existing code via something like `image_model_output = model.layers[-2]`.

**Comment by whatdhack** [comment]
@ahundt ,   backward compatibility is the main issue.   The Python keyword None  has already been  taken by being the default. Being able  to  set output layer by the way you suggested (e.g. model.layers[-2]) is  a cleaner solution. Not sure that would work for non-Sequential models.  The current implementation of VGG16 has a few if-the-else statements that would make a such an approach difficult if not impossible. 

Might  be better to start with a clean slate in  a new version instead.

**Comment by taehoonlee** [comment]
@whatdhack, @ahundt, Please note that:  

|                                       | bottleneck             |
|---------------------------------------|------------------------|
| ResNet50                              | avg_pool (1x1)         |
| VGG16, VGG19                          | block5_pool (7x7)      |
| DenseNet121, DenseNet169, DenseNet201 | bn (7x7)               |
| InceptionV3                           | mixed10 (8x8)          |
| InceptionResNetV2                     | conv_7b_ac (8x8)       |
| MobileNet                             | conv_pw_13_relu (7x7)  |
| MobileNetV2                           | out_relu (7x7)         |
| NASNetLarge                           | activation_260 (11x11) |
| NASNetMobile                          | activation_188 (7x7)   |

All except `ResNet50` (not `VGG`) have the same size bottlenecks (just before the statement `if include_top`). In most models' blocks, 2x-downsampling is followed by convs, but in `VGG`s' blocks, the downsampling follows convs. Thus, it is not so good to decouple `block5_pool` from `block5_conv1`, `block5_conv2`, and `block5_conv3`, because they are originally proposed as a single unit block.

When `include_top=False`, I think it is good to return a 7x7 feature map for a consistency over `keras-applications`. However, it is reasonable to return a 14x14 feature map if there are many use-cases. The Faster RCNN uses `block5_conv3` (14x14) instead of `block5_pool` (7x7). @whatdhack, Is there any references using a 14x14 feature map as a final feature, besides the Faster RCNN?

If there are not many examples, using the method like `image_model_output = model.layers[-2]` proposed by @ahundt is better than breaking the consistency.

**Comment by whatdhack** [comment]
@taehoonlee , that is a great analysis. You are right,  Faster-RCNN is the most well known uses case.   The  "image_model_output = model.layers[-2]"  approach seems to work.  
nn1 = applications.VGG16(weights='imagenet', include_top=False, pooling= None)
nn2 = Model (input=nn1.input, outputs=nn1.layers[-2].output)
nn2.predict() 
 
Thanks to you both for the suggestion.  I ma closing the issue.

**Pull request closed without merging**
